# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_translation_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='doc_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
